apiVersion: v1
kind: Service
metadata:
  name: prometheus-webhook-dingtalk-headless
  namespace: {{ .Release.Namespace }} 
  labels:
    app: prometheus-webhook-dingtalk
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None
  selector:
    app: prometheus-webhook-dingtalk
